name: GitHub Actions Getting Started ECR Test
run-name: ${{github.actor}} is testing out Github Actions with ECR Image
on: [push]
jobs:
  ecr_login:
    runs-on: ubuntu-latest
    outputs:
        ecr_password: ${{ steps.retrieve_password.outputs.ecr_password}}
    steps:
      - run: echo "The github action job was automatigically triggered by a ${{github.event_name}} event."
      - name: Setup AWS CLI
        uses: chrislennon/action-aws-cli@1.1
      - id: retrieve_password
        name: Retrieve ECR credentials
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.REGION}}
        #run: echo "ecr_password=Test_PWD_VALUE" >> $GITHUB_OUTPUT
        run: echo "ecr_password=$(aws ecr get-login-password)" >> "$GITHUB_OUTPUT"
        #run: echo "::set-output name=ecr_password::$(aws ecr get-login-password)"
  
  run_container:
    needs: ecr_login
    runs-on: ubuntu-latest
    env:
      PASS: ${{needs.ecr_login.outputs.ecr_password}}
    container:
      image: 282904853176.dkr.ecr.us-west-2.amazonaws.com/github-runner-playground:latest
      credentials:
        username: AWS
        password: ${{needs.ecr_login.outputs.ecr_password}}
    steps:
        - run: echo "Running from inside container pulled from ECR"
        - name: Get Container OS Info
          run: |
            cat /etc/os-release
        #- name: Checkout repository
        #  uses: actions/checkout@v4
        - run: echo $GITHUB_WORKSPACE
        - run: echo ${{github.workspace}}
        - name: Read the files in the repository
          run: |
            ls $GITHUB_WORKSPACE
        - run: echo "Completed successfully"
        
